### ISSUE TITLE
SX1262/SX1268 support

### ISSUE THREAD

**Issue by tomasbrincil** [markqvist/RNode_Firmware#10]
Hi there, I really like this project.
I am interested in SX1262. I was checking LoRa class and you did very hard work there.
How difficult would be to implement another RD module?
Regards!

**Comment by markqvist** [comment]
Support for SX1262 is coming in the relatively near future. Stay tuned :)

**Comment by markqvist** [comment]
Closing this for now, as it's not an issue as such. You are still welcome to ask any follow-up questions here though.

**Comment by tomasbrincil** [comment]
Hi Mark,
I see a huge improvment there. Still I would like to use sx1262. From code it looks like sx1276 only is supported.
Original LoRa.c from Sandeep Mistry works only with 127X family. I guess due to simplicity you dont want use all heavy RadioLib library but have you considered some solution for sx1262 support? Thank you! I can help with a code, or support hardware or kofi.

**Comment by markqvist** [comment]
SX1262 support is coming. I will release more info soon, but I am actively working on this. If you have any specific boards you would like to see supported, would you mind listing them here? Also, hardware donations in this direction are very much appreciated, and will help definitely help out :)

**Comment by markqvist** [comment]
Actually, I will reopen this, just so there is visibility about it for others with the same interest.

**Comment by khimaros** [comment]
i'm also trying to setup an RNode on my TTBeam 1.1.

this is the specific board that i have:

https://www.aliexpress.us/item/2255801100907218.html?spm=a2g0o.order_list.0.0.58091802dPVCTN&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US

**Comment by markqvist** [comment]
Thanks for the report @khimaros, and thanks for the resources. Meshtastic uses radiolib to actually handle interfacing with the LoRa modules (as far as I remember) whereas the RNode firmware uses it's own custom driver directly (since we need a really tight and interrupt-driven implementation to get the kind of performance we need, especially in terms of CSMA performance). This means that I need to write a new driver for SX1262 chips.

It's not really a big deal, and not even really a big project as such, I simply have not had time to complete it yet, because other things have been prioritised higher.

At the (extremely low) level of funding and resources I currently have, things just have to be prioritised tightly in terms of what is providing most real-world benefit at any given point.

Hopefully we can add SX1262 (and family) support soon. You are very welcome to help out with donations!

**Comment by markqvist** [comment]
I received a donation to cover hardware expenses related to implementing SX1262/68 support. The boards are now ordered and should be here soon.

**Comment by markqvist** [comment]
OK, so devices came in, and of course they have the *old chips*. Great. I will order some new ones and hope I get lucky this time around. If anyone has a reputable source for devices with SX1262 chips (T-Beams for example), please let me know.

**Comment by madbird99** [comment]
[AliExpress](https://www.aliexpress.com/)
[CDSENET Official Store](https://www.aliexpress.com/store/2798183?spm=a2g0o.detail.1000007.1.f9ac4f62xhWm54)

**Comment by markqvist** [comment]
Thanks @madbird99, but I'm looking specifically for T-Beam boards with the SX1262/SX1268 chips, not raw modules.

**Comment by markqvist** [comment]
Ah wait, I did find some there now. Last time I looked I could only find them with SX1276 chips, or listings that were unclear on what chip was used.

**Comment by markqvist** [comment]
Ok, new boards ordered. Hopefully they have the SX1262/SX1268 chips this time around :)

**Comment by khimaros** [comment]
@markqvist if you still have trouble getting your hands on the right chip after the latest, i'd be happy to send you one of mine.

**Comment by markqvist** [comment]
Thanks @khimaros! It took a while, but the boards I ordered finally arrived a short while ago, and this time around, they do actually have the SX1262 chips onboard ;) So I think I'm covered for now, but thanks a lot for the offer!

**Comment by IhorNehrutsa** [comment]
@markqvist 
Hi, Mark.
May you open a branch (pull request) with the current SX1262/SX1268 development?

**Comment by n4ijk** [comment]
I would like to offer what ever help is needed to get the heltec V3 supported. I have two of these from a meshtastic project I'm not using and would love to implement them for this.

**Comment by markqvist** [comment]
> I would like to offer what ever help is needed to get the heltec V3 supported. I have two of these from a meshtastic project I'm not using and would love to implement them for this.

Thanks! Right now the biggest obstacle is creating a general-purpose driver for the SX1262 chip, similar to the one the RNode firmware currently uses for the SX1276. If you're up for it, that's where to start!

**Comment by n4ijk** [comment]
I'm not a very hood at this type of development, but I'll give it a shot this weekend.

**Comment by keidrych** [comment]
G'Day @markqvist seasons greetings, just seeing if work on the SX1262 chips is still moving forward, do you need any help or assistance?

**Comment by jacobeva** [comment]
This work is now complete, this issue can be closed.

**Comment by markqvist** [comment]
Implemented by #55.
