### ISSUE TITLE
Repeater shift (separate TX and RX frequencies)

### ISSUE THREAD

**Issue by ivanpiter** [markqvist/RNode_Firmware#19]
Please, add setup for repeater shift (separate TX and RX frequencies).

**Comment by tomasbrincil** [comment]
Yes, I am into split mode too.

**Comment by markqvist** [comment]
Thanks for the suggestion! I actually already had this on my list of possible features, so good to know there is interest in it!

**Comment by markqvist** [comment]
This is coming in the future :)

**Comment by tomdelta** [comment]
Yes, I need it also !

Tom

**Comment by markqvist** [comment]
It will be included in the v2 release of the firmware. There us more info on that here: https://unsigned.io/rnode-a-new-model/

**Comment by whitecd** [comment]
I agree mixed Rx/Tx characteristics could be useful as a low-power repeater/bridge router.

As to V2 release, may I suggest using the Zephyr OS (https://zephyrproject.org/) as dev environment.  Zephyr is a Linux Foundation embedded ROS project. It was developed upfront with security and highly constrained SBCs.  Zephyr would supports a large number of SBCs including most of the existing RNode boards. Those not currently supported can easily be added.  There is a GSOC effort to support the MBED ardruino framework under Zephyr.

**Comment by whitecd** [comment]
There is a new (GSOC 2022) project ( https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core) that may assist in a "quick" port of the existing V1.x Arduino framework to Zephyr while you work a native V2 port.  This GSOC effort is a port of MBED's Arduino framework into Zephyr.  I don't know how robust it is to date, but it supposedly works at least at an alpha stage.
Zephyr will give you robust OTA FW upgrades (MCUBoot) as well as robust radio support/abstraction.

**Comment by markqvist** [comment]
Thanks for bringing that up, I will look into it!

**Comment by markqvist** [comment]
No takers for implementation. Closing as out of scope for now.
