### ISSUE TITLE
SX1268 support

### ISSUE THREAD

**Issue by IhorNehrutsa** [markqvist/RNode_Firmware#21]
Hello Mark.
I am interested to compile RNode firmware with [E22-400M30S](https://www.cdebyte.com/products/E22-400M30S) based on **SX1268** 433/470MHz SPI SMD LoRa Module
on generic ESP32 board

[E22-400M30S_UserManual_EN_v1.3.pdf](https://github.com/markqvist/RNode_Firmware/files/9762853/E22-400M30S_UserManual_EN_v1.3.pdf)

Thanks.

**Comment by markqvist** [comment]
For reference, see https://github.com/markqvist/RNode_Firmware/issues/10, since it is the same chip interface, just different RF frontend.
