### ISSUE TITLE
python + libusb

### ISSUE THREAD

**Issue by killabit** [markqvist/RNode_Firmware#28]
How much would would it entail to make the flashing script work in browser?  I'm not a coder but if this isn't a big deal i'm willing to hire someone to do this as a way to help this project grow by making the on ramp much easier.. 

lmk, 

p.s. finally got the new board and setup everything working flawlessly on the ObeliskOne Secure Mobile.

**Comment by markqvist** [comment]
This is coming, but with the current priorities and time, I have no guarantees as to when. I'll close this as it is not an issue per se, but feel free to open a discussion post about the idea instead.
