### ISSUE TITLE
OLED burn-in risk

### ISSUE THREAD

**Issue by faragher** [markqvist/RNode_Firmware#37]
Many OLED screens have burn-in issues, and I'm concerned a 24/7 base station will destroy the OLED screen quite quickly. Is it possible to turn off the screen remotely, or set a configuration bit that will turn off the screen after a certain length of time? I realize it's a complicated consideration as to how it turns off and on, but for an always-on unit, it seems only a matter of time before it burns in.

**Comment by markqvist** [comment]
This is now implemented, and due to be released in RNS version ``0.5.1`` and RNode Firmware ``1.60``.
