### ISSUE TITLE
T beam Ver 1.1 no display using the Adafruit 1306 four pin OLED

### ISSUE THREAD

**Issue by raytechnical** [markqvist/RNode_Firmware#38]
Hi,
Has anyone know how to get the four pin 1306 display to work on the T beam ver 1.1?

It works fine in Meshtastic, looking at the code it is configured for the 1306 multi pin version using pin 13 for the reset.

Many thanks.

**Comment by markqvist** [comment]
This should be working now that it is possible to define a custom display address with `rnodeconf`.
