### ISSUE TITLE
Feature request: support to enable wifi hotspot on esp32 boards

### ISSUE THREAD

**Issue by megabyte2010** [markqvist/RNode_Firmware#40]
It would simplify  the usability of the device, enabling any device with wifi connection to communicate with the lora network.

**Comment by NiklasCa** [comment]
+1
This would really be useful!

**Comment by mdallaire** [comment]
Having the RNode interface accessible over a tcp:// socket would be awesome. A wifi client mode could also be useful.

1- Connect the RNode to the local wifi network
2- Set it up on the roof
3- Have an indoor server running reticulum that connect and use the RNode over the TCP socket.

**Comment by markqvist** [comment]
No takers for implementation. Closing as out of scope for now.
