### ISSUE TITLE
Can't install on to Heltec LoRa32 v2 Using RNode Configuration Utility

### ISSUE THREAD

**Issue by ZL1LAC** [markqvist/RNode_Firmware#42]
Hello I can't seem to get the RNode Configuration Utility to work with the Heltec LoRa32 v2.

When I select it in the list it says "That device type does not exist, exiting now."
![image](https://github.com/markqvist/RNode_Firmware/assets/909007/345593c1-9ec6-40b7-9866-2ab93fc337ee)

The readme states this is a supported device, so I'm guessing this isn't where I go to get this board ready to go?

Hopefully someone can help me figure this out.

**Comment by Erethon** [comment]
That device is indeed supported, there's a small bug however in the device selection menu. If you apply the change from [this PR](https://github.com/markqvist/Reticulum/pull/330) it should work I believe.

**Comment by ZL1LAC** [comment]
@Erethon I assume I would have to build this and then install?  I'm not familiar with this could you point me in the direction to do this?

**Comment by Erethon** [comment]
> @Erethon I assume I would have to build this and then install? I'm not familiar with this could you point me in the direction to do this?

No building is required, you can just edit the python code that's installed on your machine. If you don't know where that is (it depends on how you installed the software and which operating system you're using), maybe it's simpler to do `pip install git+https://github.com/erethon/reticulum.git@rnodeconf-device-selection` to install the version with the bugfix for now.
