### ISSUE TITLE
Support for Heltec LoRa 32 with ESP32-S3(beta3) chip?

### ISSUE THREAD

**Issue by PeterGrace** [markqvist/RNode_Firmware#43]
I purchased a Heltec LoRa 32 board for another project but figured I'd play with RNode after a friend suggested this project.  It appears to have an ESP32-S3 chipset on it.  Is there support planned for this chipset?

**Comment by markqvist** [comment]
It's coming (together with SX1262/1268 support), and I already have the hardware needed to work on it, but I can't tell you when exactly.

I'll close this, since it's already discussed in #10 :)
