### ISSUE TITLE
Nomadnet transfer issues with more than 2 RNodes saturating the channel

### ISSUE THREAD

**Issue by SebastianObi** [markqvist/RNode_Firmware#44]
The error affects several users and can be exactly reproduced.
All details and already performed test scenarios can be found in the discussion.

I hope that Mark will find time to look at this problem.

Thanks

_Originally posted by @SebastianObi in https://github.com/markqvist/Reticulum/discussions/327_

**Comment by markqvist** [comment]
This has been significantly improved in v1.64. Closing for now.
