### ISSUE TITLE
Adding neopixel to the homebrew boards

### ISSUE THREAD

**Issue by T00ManySecrets** [markqvist/RNode_Firmware#47]
Hello can you possibly add the neopixel to the homebrew esp32 version of the firmware?
It would also be nice to have a firmware where we can manually set all aditional pins. In this way most esp32 boards would be supported. Some smaller boards dont have all pins needed.

Really like your project. Currently planing of carpeting my whole town with Rnodes. Building up the nodes. 

Can the nodes relay data without them being connected to other hardware?

**Comment by markqvist** [comment]
No takers for implementation. Closing as out of scope for now.
