### ISSUE TITLE
LILYGO T-Echo support

### ISSUE THREAD

**Issue by nowozin** [markqvist/RNode_Firmware#48]
The [T-Echo](https://www.lilygo.cc/products/t-echo) device from LILYGO is very similar to the T-Beam devices.

Additional information:
* The T-Echo uses the SX1262 chip.
* _Meshtastic_ supports T-Beam and T-Echo and may be a useful source in case there are subtle differences ([hardware devices](https://meshtastic.org/docs/supported-hardware), [development information](https://meshtastic.org/docs/development/firmware/build))

I am happy to fund the purchase of a T-Echo device (around 80 USD for device + shipping fee) in case a developer with suitable expertise is willing to port the RNode firmware to the T-Echo devices.

**Comment by nowozin** [comment]
Ping on this.

**Comment by faragher** [comment]
Mark is currently in an area with limited connectivity, and he's the one to ask about the firmware. It will likely take more than a few days, possibly into the new year, before he can do any modifications or feasibility studies.

**Comment by nowozin** [comment]
Thanks for the information @faragher. I will be patient then :+1:

**Comment by markqvist** [comment]
No takers for implementation. Closing as out of scope for now.
