### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by jacobeva** [markqvist/RNode_Firmware#70]
There is a lack of comments throughout much of the firmware repo. Additional comments throughout would be very useful so we don't have to bother Mark all the time with questions ;)

I will consider doing this myself when I have time considering I (at least like to think) understand most of the firmware now.

**Comment by markqvist** [comment]
That'd be a very, very welcome addition :)

**Comment by jacobeva** [comment]
Issue will be addressed in the community fork.
