### ISSUE TITLE
DIY Hardware

### ISSUE THREAD

**Issue by candrist** [markqvist/RNode_Firmware#9]
Is there a way that I can use this firmware with my own LoRa Board?

I use the following modules.

E32-915T30D 1W Transceiver SX1278 SX1276 915MHz Long Range UART LoRa Module https://ebay.us/L8NcuS

**Comment by markqvist** [comment]
Yes, you are very welcome to use the RNode firmware with your own hardware, but that module will not work, since it expects UART communications. The RNode firmware is using SPI communication directly with the SX1276 module for speed and efficiency.
