### ISSUE TITLE
RAK4361 Failure 

### ISSUE THREAD

**Issue by ToxicityKingETN** [markqvist/RNode_Firmware#92]
RAK fails to flash RNODE firmware after using rnodeconf, after receiving notification that device was programmed, when it attempts to verify by opening the previously used com port it will either fail, or rnode will fail to respond.
I believe the port fails because when the RAK reboots it does not automatically enter dfu mode, so the port may be different than the one used during the install(i.e. when mine was in DFU, it was COM5, but after reboot it was COM4.
As for the Rnode not responding for verification or to attempt to enable ble, I am not able to tell the reason.

**To Reproduce**
Describe in detail how to reproduce the bug.
![Screenshot 2024-10-12 231301](https://github.com/user-attachments/assets/83438ef2-9f4e-48e6-8b84-27ee5a29f87b)

**System Information**
- Windows 11
- Python 3.12

**Additional context**
Keep up the good work and thank you for your efforts!

**Comment by markqvist** [comment]
Thanks for reporting! Just calling in @jacobeva on this one too.

**Comment by ToxicityKingETN** [comment]
Additional, tried flashing it from my linux machine to see if it was windows reassigning the com port. Still failed.
Here it is as ACM1, after flashing, nRF52 reboots, then changes com port again
![Screenshot 2024-10-13 232701](https://github.com/user-attachments/assets/5803a15f-90e1-4027-b413-c87d5d9696a0)
Changed com port
![Screenshot 2024-10-13 232846](https://github.com/user-attachments/assets/0b050efd-26eb-4937-92c9-09fe6f9af2a5)

**Comment by jacobeva** [comment]
Yeah, I've had this issue from time to time as well. Sometimes the RAK4631 jumps ports. I can't really say why at the moment, it seems somewhat random. I will take this opportunity to mention again that we should really be targeting devices by `/dev/serial/by-id` in `rnodeconf` ;)

Sorry for taking so long to respond. But I think that's basically the long and short of it. Don't know why it happens, and targeting the device a different way is currently the only way I can think of fixing it (unless this is related to the USB serial in some way, which is possible).
